### ISSUE TITLE
Python client can't find existing table.

### ISSUE THREAD

**Issue by thmour** [voldemort/voldemort#237]
Using ubuntu server, I've cloned the git repo, ran `ant release` then i run

```
$ bin/voldemort-server.sh config/single_node_cluster &
```

I run the shell test via tcp and the table works, adding some sample data.
Then I ran (py 2.7)
```
$ sudo python setup.py install
```

Then I tried running this code:
```
from voldemort import StoreClient

s = StoreClient('test', [('localhost', 6666)])

s.get('a')
```

I get this error:
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 451, in put
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 413, in _fetch_version
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 375, in get
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 334, in _execute_request
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 367, in _get
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 360, in _get_with_connection
  File "build/bdist.linux-x86_64/egg/voldemort/client.py", line 288, in _check_error
voldemort.client.VoldemortException: u"Unknown store 'test'."
```

On initiating the store object I get this output from voldemort:
```
[17:40:32,829 voldemort.server.socket.SocketServerSession] INFO Client /127.0.0.1:42160 connected successfully with protocol pb0 [voldemort-server-0]
[17:40:33,372 voldemort.server.socket.SocketServerSession] INFO Client /127.0.0.1:42160 disconnected. [voldemort-server-0]
[17:40:33,379 voldemort.server.socket.SocketServerSession] INFO Client /127.0.0.1:42161 connected successfully with protocol pb0 [voldemort-server-1]
```

What's going on here?

**Comment by arunthirupathi** [comment]
Try running the java client  or admin client and see if you have a store
named test.

bin/vadmin.sh meta get stores.xml --url tcp://localhost:6667

Thanks,
Arun.

**Comment by thmour** [comment]
Previous comment: "I run the shell test via tcp and the table works, adding some sample data."

So running
```
$ bin/voldemort-shell.sh test tcp://localhost:666
$ > put 'a' '6'
$ > get 'a'
$ version(0:1) ts:1422657430360: "6"
$ >
```
Doesn't mean I got a store named test?

**Comment by arunthirupathi** [comment]
I am not familiar with Python Client. Some one from the community can
probably help you, otherwise you are going to have an adventure of your
own.

Let us know if you find something interesting.

Thanks,
Arun.

**Comment by thmour** [comment]
I tried to debug it, and it turns out the response contains the error. Maybe the code doesn't create a valid connection. I don't have the knowledge to fix it, and I don't have the time and I don't like adcventures. Making a client that fails on the most basic stuff is not good. This should be fixed.

**Comment by arunthirupathi** [comment]
Python is a fun client built and maintained by enthusiasts. Java is battle
tested.

Thanks,
Arun.
