### ISSUE TITLE
ConcurrentHashMap.keySet() NoSuchMethodError

### ISSUE THREAD

**Issue by kapiliitr** [voldemort/voldemort#385]
I have jdk1.8.0_74 installed on my system. I am getting the error-
Exception in thread "main" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at voldemort.store.metadata.MetadataStore.updateRoutingStrategies(MetadataStore.java:526)
        at voldemort.store.metadata.MetadataStore.init(MetadataStore.java:690)
        at voldemort.store.metadata.MetadataStore.<init>(MetadataStore.java:131)
        at voldemort.store.metadata.MetadataStore.readFromDirectory(MetadataStore.java:159)
        at voldemort.server.VoldemortServer.<init>(VoldemortServer.java:89)
        at voldemort.server.VoldemortServer.main(VoldemortServer.java:382)

It is same as the error I found online here- https://gist.github.com/AlainODea/1375759b8720a3f9f094

**Comment by arunthirupathi** [comment]
What version of Voldemort are you using?

Try the latest master.

https://github.com/voldemort/voldemort/commit/3378d6cba0a06bfbb6e2871d8008e425cfbed7ab

Thanks,
Arun.

**Comment by kapiliitr** [comment]
1.6
I downloaded the latest release from project-voldemort.com

**Comment by FelixGV** [comment]
Hi Kapil,

I'm sorry that the website contained misleading information. I've fixed it.

The latest version is currently 1.10.13, and it contains the fix that Arun mentioned.

-F

**Comment by kapiliitr** [comment]
It works now :)

Regards,
Kapil Agarwal

**Comment by arunthirupathi** [comment]
BTW, JAVA 6 is End Of Life and on latest master the minimum requirement is
increased. We are running Voldemort on Java 8 and not actively trying it
out on other versions.

So we highly recommend you to move to Java 8, if you haven't already moved.

Thanks,
Arun.
