### ISSUE TITLE
Get 'lang.OutOfMemoryError: Java heap space' exception when update entries from file

### ISSUE THREAD

**Issue by ARES-Z** [voldemort/voldemort#401]
When i attemp to update entries from file ,but i got the exception on the following：

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at voldemort.tools.admin.command.AdminCommandStream$1.computeNext(AdminCommandStream.java:1018)
    at voldemort.tools.admin.command.AdminCommandStream$1.computeNext(AdminCommandStream.java:1006)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at voldemort.client.protocol.admin.AdminClient$StreamingOperations.streamingUpdateEntries(AdminClient.java:2644)
    at voldemort.client.protocol.admin.AdminClient$StreamingOperations.updateEntries(AdminClient.java:2574)
    at voldemort.tools.admin.command.AdminCommandStream$SubCommandStreamUpdateEntries.doStreamUpdateEntries(AdminCommandStream.java:980)
    at voldemort.tools.admin.command.AdminCommandStream$SubCommandStreamUpdateEntries.executeCommand(AdminCommandStream.java:950)
    at voldemort.tools.admin.command.AdminCommandStream.executeCommand(AdminCommandStream.java:91)
    at voldemort.tools.admin.command.AdminCommand.executeCommand(AdminCommand.java:51)
    at voldemort.tools.admin.VAdminTool.main(VAdminTool.java:30)
```

How can i update the entries in the file?

**Comment by arunthirupathi** [comment]
What is the command you are running ?

Thanks,
Arun.

**Comment by ARES-Z** [comment]
the command i used is :
`bin/vadmin.sh stream update-entries --dir /data/voldemort-entries/ --node 0 --url tcp://$voldemort_host:$voldemort_post`

**Comment by arunthirupathi** [comment]
Try increasing the Voldmeort Options to 16G or 32G to see if the issue goes
away.

VOLD_OPTS="-Xmx2G -server -Dcom.sun.management.jmxremote "

https://github.com/voldemort/voldemort/blob/master/bin/run-class.sh#L43

If the issue reproduces consistently even after that, try attaching
jvisualvm and see what are the top objects reatined by size. I could not
find.

On taking a cursory look at the code, all the opened file handles are never
closed, there by leaking the file handle and the buffered output stream.

Other mitigation you can do is split the load operation into multiple
batches by running for few stores at a time.

We haven't run this command except for some debugging and other purposes
and this command is not resilient as others used in the main stream path.

Lastly, if you want to fix the problem, please send us a pull request and
we will be  happy to merge it in.

Thanks,
Arun.

**Comment by ARES-Z** [comment]
I found the reason for the problem after looking at the code, i will try to fix it.

Thanks Arun !
